import type { Env } from './types';

export const NAMESPACE_META: Record<string, { name: string; category: string; binding: string }> = {
  'courts-supreme-court': { name: 'Supreme Court', category: 'Courts', binding: 'EMAIL_COURTS_SUPREME_COURT' },
  'courts-court-of-appeals-civil-division': { name: 'Court of Appeals Civil Division', category: 'Courts', binding: 'EMAIL_COURTS_COURT_OF_APPEALS_CIVIL_DIVISION' },
  'courts-kings-bench-appeals-division': { name: "King's Bench Appeals Division", category: 'Courts', binding: 'EMAIL_COURTS_KINGS_BENCH_APPEALS_DIVISION' },
  'courts-chancery-division': { name: 'Chancery Division', category: 'Courts', binding: 'EMAIL_COURTS_CHANCERY_DIVISION' },
  'courts-administrative-court': { name: 'Administrative Court', category: 'Courts', binding: 'EMAIL_COURTS_ADMINISTRATIVE_COURT' },
  'courts-central-london-county-court': { name: 'Central London County Court', category: 'Courts', binding: 'EMAIL_COURTS_CENTRAL_LONDON_COUNTY_COURT' },
  'courts-clerkenwell-county-court': { name: 'Clerkenwell County Court', category: 'Courts', binding: 'EMAIL_COURTS_CLERKENWELL_COUNTY_COURT' },
  'complaints-ico': { name: 'ICO', category: 'Complaints', binding: 'EMAIL_COMPLAINTS_ICO' },
  'complaints-phso': { name: 'PHSO', category: 'Complaints', binding: 'EMAIL_COMPLAINTS_PHSO' },
  'complaints-parliament': { name: 'Parliament', category: 'Complaints', binding: 'EMAIL_COMPLAINTS_PARLIAMENT' },
  'complaints-hmcts': { name: 'HMCTS', category: 'Complaints', binding: 'EMAIL_COMPLAINTS_HMCTS' },
  'complaints-bar-standards-board': { name: 'Bar Standards Board', category: 'Complaints', binding: 'EMAIL_COMPLAINTS_BAR_STANDARDS_BOARD' },
  'expenses-legal-fees-claimant': { name: 'Legal Fees - Claimant', category: 'Legal Expenses', binding: 'EMAIL_EXPENSES_LEGAL_FEES_CLAIMANT' },
  'expenses-legal-fees-company': { name: 'Legal Fees - Company', category: 'Legal Expenses', binding: 'EMAIL_EXPENSES_LEGAL_FEES_COMPANY' },
  'expenses-legal-fees-director': { name: 'Legal Fees - Director', category: 'Legal Expenses', binding: 'EMAIL_EXPENSES_LEGAL_FEES_DIRECTOR' },
  'expenses-repairs': { name: 'Repairs', category: 'Legal Expenses', binding: 'EMAIL_EXPENSES_REPAIRS' },
  'claimant-hk-law': { name: 'HK Law', category: 'Claimants', binding: 'EMAIL_CLAIMANT_HK_LAW' },
  'claimant-lessel': { name: 'Lessel', category: 'Claimants', binding: 'EMAIL_CLAIMANT_LESSEL' },
  'claimant-liu': { name: 'Liu', category: 'Claimants', binding: 'EMAIL_CLAIMANT_LIU' },
  'claimant-rentify': { name: 'Rentify', category: 'Claimants', binding: 'EMAIL_CLAIMANT_RENTIFY' },
  'defendants-defendant': { name: 'Defendant', category: 'Defendants', binding: 'EMAIL_DEFENDANTS_DEFENDANT' },
  'defendants-both-defendants': { name: 'Both Defendants', category: 'Defendants', binding: 'EMAIL_DEFENDANTS_BOTH_DEFENDANTS' },
  'defendants-barristers': { name: 'Barristers', category: 'Defendants', binding: 'EMAIL_DEFENDANTS_BARRISTERS' },
  'defendants-litigant-in-person-only': { name: 'Litigant in Person Only', category: 'Defendants', binding: 'EMAIL_DEFENDANTS_LITIGANT_IN_PERSON_ONLY' },
  'defendants-mobicycle-ou-only': { name: 'MobiCycle OU Only', category: 'Defendants', binding: 'EMAIL_DEFENDANTS_MOBICYCLE_OU_ONLY' },
  'government-uk-legal-department': { name: 'UK Legal Department', category: 'Government', binding: 'EMAIL_GOVERNMENT_UK_LEGAL_DEPARTMENT' },
  'government-estonia': { name: 'Estonia', category: 'Government', binding: 'EMAIL_GOVERNMENT_ESTONIA' },
  'government-us-state-department': { name: 'US State Department', category: 'Government', binding: 'EMAIL_GOVERNMENT_US_STATE_DEPARTMENT' },
  'reconsideration-single-judge': { name: 'Single Judge', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_SINGLE_JUDGE' },
  'reconsideration-court-officer-review': { name: 'Court Officer Review', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_COURT_OFFICER_REVIEW' },
  'reconsideration-pta-refusal': { name: 'PTA Refusal', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_PTA_REFUSAL' },
  'reconsideration-cpr52-24-5': { name: 'CPR 52.24(5)', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_CPR52_24_5' },
  'reconsideration-cpr52-24-6': { name: 'CPR 52.24(6)', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_CPR52_24_6' },
  'reconsideration-cpr52-30': { name: 'CPR 52.30', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_CPR52_30' },
  'reconsideration-pd52b': { name: 'PD52B', category: 'Reconsideration', binding: 'EMAIL_RECONSIDERATION_PD52B' },
};

export function getKVBindings(env: Env): Record<string, KVNamespace> {
  return {
    RAW_DATA_HEADERS: env.RAW_DATA_HEADERS,
    FILTERED_DATA_HEADERS: env.FILTERED_DATA_HEADERS,
    EMAIL_COURTS_SUPREME_COURT: env.EMAIL_COURTS_SUPREME_COURT,
    EMAIL_COURTS_COURT_OF_APPEALS_CIVIL_DIVISION: env.EMAIL_COURTS_COURT_OF_APPEALS_CIVIL_DIVISION,
    EMAIL_COURTS_KINGS_BENCH_APPEALS_DIVISION: env.EMAIL_COURTS_KINGS_BENCH_APPEALS_DIVISION,
    EMAIL_COURTS_CHANCERY_DIVISION: env.EMAIL_COURTS_CHANCERY_DIVISION,
    EMAIL_COURTS_ADMINISTRATIVE_COURT: env.EMAIL_COURTS_ADMINISTRATIVE_COURT,
    EMAIL_COURTS_CENTRAL_LONDON_COUNTY_COURT: env.EMAIL_COURTS_CENTRAL_LONDON_COUNTY_COURT,
    EMAIL_COURTS_CLERKENWELL_COUNTY_COURT: env.EMAIL_COURTS_CLERKENWELL_COUNTY_COURT,
    EMAIL_COMPLAINTS_ICO: env.EMAIL_COMPLAINTS_ICO,
    EMAIL_COMPLAINTS_PHSO: env.EMAIL_COMPLAINTS_PHSO,
    EMAIL_COMPLAINTS_PARLIAMENT: env.EMAIL_COMPLAINTS_PARLIAMENT,
    EMAIL_COMPLAINTS_HMCTS: env.EMAIL_COMPLAINTS_HMCTS,
    EMAIL_COMPLAINTS_BAR_STANDARDS_BOARD: env.EMAIL_COMPLAINTS_BAR_STANDARDS_BOARD,
    EMAIL_EXPENSES_LEGAL_FEES_CLAIMANT: env.EMAIL_EXPENSES_LEGAL_FEES_CLAIMANT,
    EMAIL_EXPENSES_LEGAL_FEES_COMPANY: env.EMAIL_EXPENSES_LEGAL_FEES_COMPANY,
    EMAIL_EXPENSES_LEGAL_FEES_DIRECTOR: env.EMAIL_EXPENSES_LEGAL_FEES_DIRECTOR,
    EMAIL_EXPENSES_REPAIRS: env.EMAIL_EXPENSES_REPAIRS,
    EMAIL_CLAIMANT_HK_LAW: env.EMAIL_CLAIMANT_HK_LAW,
    EMAIL_CLAIMANT_LESSEL: env.EMAIL_CLAIMANT_LESSEL,
    EMAIL_CLAIMANT_LIU: env.EMAIL_CLAIMANT_LIU,
    EMAIL_CLAIMANT_RENTIFY: env.EMAIL_CLAIMANT_RENTIFY,
    EMAIL_DEFENDANTS_DEFENDANT: env.EMAIL_DEFENDANTS_DEFENDANT,
    EMAIL_DEFENDANTS_BOTH_DEFENDANTS: env.EMAIL_DEFENDANTS_BOTH_DEFENDANTS,
    EMAIL_DEFENDANTS_BARRISTERS: env.EMAIL_DEFENDANTS_BARRISTERS,
    EMAIL_DEFENDANTS_LITIGANT_IN_PERSON_ONLY: env.EMAIL_DEFENDANTS_LITIGANT_IN_PERSON_ONLY,
    EMAIL_DEFENDANTS_MOBICYCLE_OU_ONLY: env.EMAIL_DEFENDANTS_MOBICYCLE_OU_ONLY,
    EMAIL_GOVERNMENT_UK_LEGAL_DEPARTMENT: env.EMAIL_GOVERNMENT_UK_LEGAL_DEPARTMENT,
    EMAIL_GOVERNMENT_ESTONIA: env.EMAIL_GOVERNMENT_ESTONIA,
    EMAIL_GOVERNMENT_US_STATE_DEPARTMENT: env.EMAIL_GOVERNMENT_US_STATE_DEPARTMENT,
    EMAIL_RECONSIDERATION_SINGLE_JUDGE: env.EMAIL_RECONSIDERATION_SINGLE_JUDGE,
    EMAIL_RECONSIDERATION_COURT_OFFICER_REVIEW: env.EMAIL_RECONSIDERATION_COURT_OFFICER_REVIEW,
    EMAIL_RECONSIDERATION_PTA_REFUSAL: env.EMAIL_RECONSIDERATION_PTA_REFUSAL,
    EMAIL_RECONSIDERATION_CPR52_24_5: env.EMAIL_RECONSIDERATION_CPR52_24_5,
    EMAIL_RECONSIDERATION_CPR52_24_6: env.EMAIL_RECONSIDERATION_CPR52_24_6,
    EMAIL_RECONSIDERATION_CPR52_30: env.EMAIL_RECONSIDERATION_CPR52_30,
    EMAIL_RECONSIDERATION_PD52B: env.EMAIL_RECONSIDERATION_PD52B,
  };
}
